#!/usr/bin/env bats

# ============================================================================
# test/setup-repo.bats — smoke test for setup-repo.sh (Fase 0.2)
# ============================================================================
# setup-repo.sh locates its own source tree via BASH_SOURCE, so it can be
# invoked by absolute path from anywhere. Each test builds a throwaway git
# repo under a temp dir and runs the real setup-repo.sh against it — nothing
# here touches the AI-Setup repo itself.
# ============================================================================

setup() {
  AI_SETUP_ROOT="$(cd "$(dirname "$BATS_TEST_DIRNAME")" && pwd)"
  SETUP_REPO_SH="$AI_SETUP_ROOT/setup-repo.sh"
  TARGET_DIR="$(mktemp -d)"
  cd "$TARGET_DIR"
  git init -q
  # setup-repo.sh's Node-detection branch only changes echoed instructions,
  # not files written — no package.json needed for these tests.
}

teardown() {
  cd "$AI_SETUP_ROOT"
  rm -rf "$TARGET_DIR"
}

tree_hash() {
  # Content + path hash, excluding .git — same recipe update-plan-aug-2026.md
  # 0.2 specifies (find | sort + sha256sum).
  find "$TARGET_DIR" -type f -not -path '*/.git/*' | sort | xargs sha256sum | sha256sum
}

@test "setup-repo.sh refuses to run outside a git repo" {
  non_git_dir="$(mktemp -d)"
  cd "$non_git_dir"
  run bash "$SETUP_REPO_SH"
  [ "$status" -ne 0 ]
  rm -rf "$non_git_dir"
}

@test "setup-repo.sh creates every destination the README's 'What goes where' table declares" {
  bash "$SETUP_REPO_SH" >/dev/null

  [ -d "$TARGET_DIR/scripts" ]
  for f in "$AI_SETUP_ROOT"/registry/scripts/*.js; do
    [ -f "$TARGET_DIR/scripts/$(basename "$f")" ]
  done

  [ -f "$TARGET_DIR/.githooks/pre-commit" ]
  [ -f "$TARGET_DIR/.githooks/prepare-commit-msg" ]
  [ -f "$TARGET_DIR/.githooks/post-merge" ]
  [ -f "$TARGET_DIR/.githooks/pre-push" ]
  [ -x "$TARGET_DIR/.githooks/pre-commit" ]
  [ "$(git -C "$TARGET_DIR" config core.hooksPath)" = ".githooks" ]

  [ -f "$TARGET_DIR/.github/workflows/pr-validation.yml" ]
  [ -f "$TARGET_DIR/.github/workflows/on-merge.yml" ]

  [ -f "$TARGET_DIR/AGENTS.md" ]
  [ -f "$TARGET_DIR/.mcp.json" ]
  [ -f "$TARGET_DIR/.env.local" ]

  # Fase 2 (update-plan-aug-2026.md): no more setup-portability.sh step, and
  # no symlinks anywhere — CLAUDE.md/GEMINI.md are real @AGENTS.md imports,
  # .cursor/mcp.json is a real copy of .mcp.json.
  [ ! -f "$TARGET_DIR/setup-portability.sh" ]
  [ -f "$TARGET_DIR/CLAUDE.md" ]
  [ ! -L "$TARGET_DIR/CLAUDE.md" ]
  [ "$(cat "$TARGET_DIR/CLAUDE.md")" = "@AGENTS.md" ]
  [ -f "$TARGET_DIR/GEMINI.md" ]
  [ ! -L "$TARGET_DIR/GEMINI.md" ]
  [ "$(cat "$TARGET_DIR/GEMINI.md")" = "@AGENTS.md" ]
  [ -f "$TARGET_DIR/.cursor/mcp.json" ]
  [ ! -L "$TARGET_DIR/.cursor/mcp.json" ]
  diff "$TARGET_DIR/.mcp.json" "$TARGET_DIR/.cursor/mcp.json"
  [ -f "$TARGET_DIR/.github/copilot-instructions.md" ]
  [ ! -L "$TARGET_DIR/.github/copilot-instructions.md" ]
  # Condensed, not a verbatim AGENTS.md copy (the bug this Fase fixed —
  # setup-portability.sh used to symlink this straight to AGENTS.md).
  grep -q "Generated by \`lib/condense.mjs\`" "$TARGET_DIR/.github/copilot-instructions.md"
  ! diff -q "$TARGET_DIR/AGENTS.md" "$TARGET_DIR/.github/copilot-instructions.md" >/dev/null

  [ -d "$TARGET_DIR/.local-docs" ]
  [ -f "$TARGET_DIR/.local-docs/plan.md" ]
  [ -f "$TARGET_DIR/.local-docs/architecture.md" ]
  [ -f "$TARGET_DIR/.local-docs/security-gaps.md" ]
  [ -f "$TARGET_DIR/.local-docs/decisions.md" ]

  for f in "$AI_SETUP_ROOT"/registry/rules/*.md; do
    [ -f "$TARGET_DIR/.claude/rules/$(basename "$f")" ]
    [ -f "$TARGET_DIR/.cursor/rules/$(basename "$f" .md).mdc" ]
  done

  [ -f "$TARGET_DIR/.claude/hooks/pre-tool-use/block-secrets.sh" ]
  [ -f "$TARGET_DIR/.claude/hooks/post-tool-use/lint-after-write.sh" ]
  [ -f "$TARGET_DIR/.claude/settings.json" ]

  grep -q "^\.env\.local$" "$TARGET_DIR/.gitignore"
  grep -q "^\.local-docs/$" "$TARGET_DIR/.gitignore"
}

@test "setup-repo.sh is idempotent: running it twice produces the same tree" {
  bash "$SETUP_REPO_SH" >/dev/null
  hash1=$(tree_hash)

  bash "$SETUP_REPO_SH" >/dev/null
  hash2=$(tree_hash)

  [ "$hash1" = "$hash2" ]
}

@test "setup-repo.sh does not overwrite an existing .mcp.json" {
  echo '{"marker":"do-not-touch"}' > "$TARGET_DIR/.mcp.json"
  bash "$SETUP_REPO_SH" >/dev/null
  grep -q "do-not-touch" "$TARGET_DIR/.mcp.json"
}

@test "setup-repo.sh does not overwrite an existing .claude/settings.json" {
  mkdir -p "$TARGET_DIR/.claude"
  echo '{"marker":"do-not-touch"}' > "$TARGET_DIR/.claude/settings.json"
  bash "$SETUP_REPO_SH" >/dev/null
  grep -q "do-not-touch" "$TARGET_DIR/.claude/settings.json"
}

@test "setup-repo.sh does not overwrite an existing .env.local" {
  echo "MARKER=do-not-touch" > "$TARGET_DIR/.env.local"
  bash "$SETUP_REPO_SH" >/dev/null
  grep -q "do-not-touch" "$TARGET_DIR/.env.local"
}

@test "setup-repo.sh does not overwrite an existing .local-docs/" {
  mkdir -p "$TARGET_DIR/.local-docs"
  echo "do-not-touch" > "$TARGET_DIR/.local-docs/plan.md"
  bash "$SETUP_REPO_SH" >/dev/null
  grep -q "do-not-touch" "$TARGET_DIR/.local-docs/plan.md"
  # And no sibling starter file (e.g. architecture.md) was added into an
  # existing .local-docs/ either — the whole folder is left alone, not
  # merged file-by-file.
  [ ! -f "$TARGET_DIR/.local-docs/architecture.md" ]
}

@test "setup-repo.sh never creates a .husky/ directory (Fase 4.1: Husky retired for native git hooks)" {
  bash "$SETUP_REPO_SH" >/dev/null
  [ ! -d "$TARGET_DIR/.husky" ]
}

@test "scripts/*.js run with plain node — no minimist / no node_modules required (Fase 4.1)" {
  bash "$SETUP_REPO_SH" >/dev/null
  [ ! -d "$TARGET_DIR/node_modules" ]
  run node "$TARGET_DIR/scripts/auto-commit.js" --help
  [ "$status" -eq 0 ]
}

@test "setup-repo.sh appends missing lines to an existing AGENTS.md without rewriting prior content" {
  cat > "$TARGET_DIR/AGENTS.md" <<'EOF'
# My Project

Custom project-specific content that must survive untouched.
EOF

  bash "$SETUP_REPO_SH" >/dev/null

  grep -q "Custom project-specific content that must survive untouched." "$TARGET_DIR/AGENTS.md"
  grep -q "Commit/PR style:" "$TARGET_DIR/AGENTS.md"
  grep -q "\.local-docs/" "$TARGET_DIR/AGENTS.md"

  # First line of the original content is still the first line of the file —
  # "append-only" means nothing was inserted before it.
  first_line=$(head -1 "$TARGET_DIR/AGENTS.md")
  [ "$first_line" = "# My Project" ]
}

@test "setup-repo.sh does not double-append AGENTS.md lines on a second run" {
  cat > "$TARGET_DIR/AGENTS.md" <<'EOF'
# My Project
EOF
  bash "$SETUP_REPO_SH" >/dev/null
  bash "$SETUP_REPO_SH" >/dev/null

  count=$(grep -c "Commit/PR style:" "$TARGET_DIR/AGENTS.md")
  [ "$count" -eq 1 ]
}

@test "setup-repo.sh never creates a symlink anywhere in the target repo (Fase 2)" {
  bash "$SETUP_REPO_SH" >/dev/null
  # -type l finds symlinks specifically; excludes .git (git itself may use
  # internal symlink-like objects on some platforms, out of scope here).
  symlinks=$(find "$TARGET_DIR" -type l -not -path '*/.git/*')
  [ -z "$symlinks" ]
}

@test "no active script in this repo uses 'ln -s' (Fase 2: symlinks retired, not just unused)" {
  # Scoped to the scripts setup-repo.sh/install.sh actually run — excludes
  # docs/archive/ (the retired setup-portability.sh is kept there verbatim,
  # on purpose, as a historical record — see its own header note) and
  # node_modules (bats' own vendored scripts, not this repo's code).
  cd "$AI_SETUP_ROOT"
  # `|| true` on each step: grep exits 1 on "no matches", which would
  # otherwise abort the test under bats' errexit before reaching the
  # actual assertion below — an empty result here is the PASSING case.
  hits=$( (grep -rl 'ln -s' --include='*.sh' . 2>/dev/null || true) \
    | (grep -v '^\./docs/archive/' || true) \
    | (grep -v '^\./node_modules/' || true) )
  [ -z "$hits" ]
}
